version: '3.1'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: OFERTATON_GRANCOLOMBIANO
      MYSQL_USER: poli
      MYSQL_PASSWORD: poli
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/OFERTATON_GRANCOLOMBIANO
      SPRING_DATASOURCE_USERNAME: poli
      SPRING_DATASOURCE_PASSWORD: poli
    depends_on:
      - db
